# Default values for backend-channeladaptor-web.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
---
replicaCount: 1

image:
  repository: 598933794066.dkr.ecr.us-west-2.amazonaws.com/converse3/frontend-engineerportal
  tag: 13-41bcd349
  pullPolicy: Always

container:
  port: 3021

env:

envSecrets:

  
service:
  type: ClusterIP
  port: 3021
  externalIPs: []

# ingress:
#   create: false
  # annotations: {}
  # host:

#ingress:
#  create: true
#  annotations:
#    kubernetes.io/ingress.class: "nginx"
#    # This should be the Nginx ELB Route 53 record set name
#    external-dns.alpha.kubernetes.io/target: ingress.converse.dev.eks.liquidstudiolondon.com
#  rules:
#  - host: webchat.converse.dev.eks.liquidstudiolondon.com
#    http:
#      paths:
#      - path: /
#        backend:
#          serviceName: frontend-mwc
#          servicePort: 3000

ingress:
 create: true
 annotations:
   kubernetes.io/ingress.class: "nginx"
   kubernetes.io/ingress.allow-http: "true"
   nginx.ingress.kubernetes.io/ssl-redirect: "false"
 rules:
  - host: dev.srv12-va.com
    http:
      paths:
      - path: /frontend-engineeringportal
        pathType: Prefix
        backend:
          service:
            name: frontend-engineerportal
            port: 
              number: 3021
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-engineerportal
            port: 
              number: 3021
resources:
  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 20m
    memory: 64Mi

nodeSelector: {}

tolerations: []

affinity: {}
