# Default values for backend-channeladaptor-web.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
---
replicaCount: 1

image:
  repository: 598933794066.dkr.ecr.us-east-1.amazonaws.com/converse3/frontend-engineerportal
  tag: latest
  pullPolicy: Always

container:
  port: 3021

env:

envSecrets:

service:
  type: ClusterIP
  port: 3021
  externalIPs: []

ingress:
  create: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
  tls:
    - hosts:
        - prod.srv4-va.com
  rules:
    - host: prod.srv4-va.com
      http:
        paths:
          - path: /frontend-engineeringportal
            backend:
              serviceName: frontend-engineerportal
              servicePort: 3021
          - path: /
            backend:
              serviceName: frontend-engineerportal
              servicePort: 3021

resources:
  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 20m
    memory: 64Mi

nodeSelector: {}

tolerations: []

affinity: {}
